pouch_header = [
    version: uint .size 1,
    encryption_info,
]

encryption_info = [
    plaintext_info //
    saead_info
]

plaintext_info = (
    encryption_type: 0,
    id: tstr,
)

saead_info = (
    encryption_type: 1,
    session: session_info,
    pouch_id: uint .size 2,
)

session_info = [
    id: session_id_random / session_id_sequential,
    initiator: device / server,
    algorithm: aes_gcm / chacha20_poly1305,
    max_block_size_log: uint .size 1,
    cert_ref: bstr .size 6,
]

session_id_random = [
    random: bstr .size 16,
]

session_id_sequential = [
    tag: bstr .size 8,
    seq: uint .size 8,
]

; Role identifiers
device = 0
server = 1

; Algorithm identifiers
chacha20_poly1305 = 1
aes_gcm = 2
